# Generated by Django 4.1.2 on 2022-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='no-avatar.jpg', upload_to='profileimg/'),
        ),
    ]
