# Generated by Django 4.1.2 on 2022-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cines',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teatros',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
