# Generated by Django 4.1.2 on 2022-10-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_cine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='teatro',
        ),
        migrations.AddField(
            model_name='post',
            name='teatro',
            field=models.ManyToManyField(blank=True, default='1', null=True, related_name='teatros', to='blog.teatros'),
        ),
    ]
