# Generated by Django 4.1.2 on 2022-10-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_fecha_post_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkyoutube',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
