# Generated by Django 4.1.2 on 2022-11-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mp3',
            field=models.FileField(blank=True, null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
