# Generated by Django 4.1.2 on 2022-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_userfavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen2',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen3',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen4',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen5',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
