# Generated by Django 4.1.2 on 2022-11-05 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_descripcion_imagen_post_descripcion_imagen2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='descripcion_imagen2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion_imagen3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion_imagen4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='descripcion_imagen5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image5',
        ),
    ]
