# Generated by Django 4.1.2 on 2022-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_descripcion_imagen2_post_descripcion_imagen4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen3',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion_imagen5',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
