# Generated by Django 4.1.2 on 2022-11-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_descripcion_imagen10_post_descripcion_imagen11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teatros',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
