# Generated by Django 4.1.2 on 2022-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_teatros_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='teatros',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
