# Generated by Django 4.1.2 on 2022-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_teatros_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='es_entrevista',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0),
        ),
    ]
