# Generated by Django 4.1.2 on 2022-11-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_post_es_entrevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='es_entrevista',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')], default=False),
        ),
    ]
