# Generated by Django 4.1.2 on 2022-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_post_es_entrevista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorites',
            name='favoritos',
        ),
        migrations.AddField(
            model_name='userfavorites',
            name='favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='blog.post'),
        ),
    ]
